name: GitHub Actions Runner
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  Create-Page:
    runs-on: ubuntu-latest
    steps:
      - name: Run complete workflow
        uses: actions/checkout@v4
      - name: Execute all steps
        run: |
          sudo apt-get install -y pandoc
          chmod +x convert.sh
          bash convert.sh
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git diff index.html
          git commit -m "Update index.html from README.md" 
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}