name: GitHub Actions Runner
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  Create-Page:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Generate index.html
        run: |
          INPUT_FILE="README.md"
          OUTPUT_FILE="index.html"

          if [[ ! -f $OUTPUT_FILE ]] || [[ $INPUT_FILE -nt $OUTPUT_FILE ]]; then
              echo "RUN PANDOC"
              pandoc "$INPUT_FILE" -o "$OUTPUT_FILE" --metadata title="GitHub Pages" -s
          fi

      - name: Show contents of index.html
        run: cat index.html

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update index.html from README.md" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
